### ISSUE TITLE
Can you pipe Captcha through terminal?

### ISSUE THREAD

**Issue by CHJ85** [microsockss/free-mp3-download-cli#1]
Hi there. I don't wanna pay for the captcha API just so that I can download music.
Can you pipe the actual captcha through instead please?
If that's even possible.

**Comment by ethanbarclay** [comment]
That sounds like a good idea, I'll look into adding this.

**Comment by ethanbarclay** [comment]
Closed with b566103.

**Comment by ethanbarclay** [comment]
I've noticed that there is an error with captcha grabbing ever so often that causes the program to crash. If this happens, just retry again. I'm working on debugging this currently.

**Comment by CHJ85** [comment]
Okay, thanks.

**Comment by ethanbarclay** [comment]
Fixed bug with f30f828.
